atom:
  # Gamma parameter for RBF covariance kernel. Higher values reduce covariance at
  # a given distance.
  gamma: 2.0

  # Atomic radius.
  radius: 0.4

  # Min and max range to consider valid scans.
  min_scan_range: 1.0
  max_scan_range: 25.0

  # Radius for nearest neighbor search for surface normal estimation. This should
  # be on the order of the voxel grid resolution if input point clouds are filtered.
  surface_normal_radius: 2.5

  # Optionally update signed distance and occupancy separately.
  update_occupancy: true
  update_signed_distance: true

  # Maximum distance to raycast into a surface (think of this as the surface
  # thickness).
  max_occupied_backoff: 2.1

  # Maximum distance to raycast into free space along the surface normal.
  max_normal_backoff: 4.1

  # Maximum number of atoms to lay down along the ray toward the robot and the
  # normal vector (both into free space).
  max_samples_normal: 3
  max_samples_ray: 10

  # Noise variance for GP signed distance function regression.
  noise: 1.0

  # Number of neighbors to examine for GP regression.
  num_neighbors: 30

  # Probability update for hits/misses.
  probability_hit: 0.7
  probability_miss: 0.3

  # Visualization topic names.
  full_occupancy_topic: occupancy
  full_sdf_topic: sdf

  # Fixed frame id.
  fixed_frame_id: world
#  fixed_frame_id: velodyne

  # Thresholds for visualizing occupied atoms and those near surfaces.
  occupied_threshold: 0.75
  sdf_threshold: 1.1

  # Boolean to visualize only those atoms that are either occupied
  # or near surfaces.
  only_show_occupied: true
